import { GasBrandItem } from '../src/types.js';

export const initialBrands: GasBrandItem[] = [
  {
    id: 'brand-total',
    name: 'TotalEnergies (Total Gas)',
    distributor: 'TotalEnergies Marketing Kenya Plc',
    tagline: 'Tamper-proof safety seal & high caloric efficiency',
    badge: 'Most Popular',
    color: '#E01E2B',
    borderColor: 'border-red-500',
    bgLight: 'bg-red-50',
    valveType: 'Screw & Pin Valve',
    cylinderSizes: ['6 kg', '13 kg', '50 kg'],
    isPopular: true,
    isAvailable: true,
    isDeleted: false
  },
  {
    id: 'brand-kgas',
    name: 'Rubis (K-Gas)',
    distributor: 'Rubis Energy Kenya',
    tagline: 'KEBS certified low-odor pure flame fuel',
    badge: 'Household Choice',
    color: '#008542',
    borderColor: 'border-emerald-600',
    bgLight: 'bg-emerald-50',
    valveType: 'Standard Universal Compact',
    cylinderSizes: ['6 kg', '13 kg', '35 kg'],
    isPopular: true,
    isAvailable: true,
    isDeleted: false
  },
  {
    id: 'brand-afrigas',
    name: 'Afrigas (Shell / Vivo)',
    distributor: 'Vivo Energy Kenya',
    tagline: 'Gold seal security valve with zero soot burn',
    badge: 'High Performance',
    color: '#FFD100',
    borderColor: 'border-amber-500',
    bgLight: 'bg-amber-50',
    valveType: 'Standard 20mm Compact',
    cylinderSizes: ['6 kg', '13 kg', '50 kg'],
    isPopular: true,
    isAvailable: true,
    isDeleted: false
  },
  {
    id: 'brand-progas',
    name: 'Pro Gas',
    distributor: 'Proto Energy Limited',
    tagline: 'Reliable fast-boil LPG with leak-tested valves',
    badge: 'Fast Delivery',
    color: '#F97316',
    borderColor: 'border-orange-500',
    bgLight: 'bg-orange-50',
    valveType: 'Universal Quick-Click',
    cylinderSizes: ['6 kg', '13 kg'],
    isPopular: true,
    isAvailable: true,
    isDeleted: false
  },
  {
    id: 'brand-mpishi',
    name: 'Mpishi Gas (SeaGas)',
    distributor: 'SeaGas Kenya Ltd',
    tagline: 'Eco-efficient blue flame with calibrated net cylinder weight',
    badge: 'Top Value',
    color: '#059669',
    borderColor: 'border-emerald-500',
    bgLight: 'bg-emerald-50',
    valveType: 'Standard Universal 20mm',
    cylinderSizes: ['6 kg', '13 kg'],
    isPopular: true,
    isAvailable: true,
    isDeleted: false
  },
  {
    id: 'brand-hashi',
    name: 'Hashi Gas',
    distributor: 'Hashi Energy Holdings',
    tagline: 'Heavy-gauge steel certified for maximum domestic safety',
    badge: 'Economy Choice',
    color: '#0284C7',
    borderColor: 'border-sky-500',
    bgLight: 'bg-sky-50',
    valveType: 'Standard Pin Valve',
    cylinderSizes: ['6 kg', '13 kg'],
    isAvailable: true,
    isDeleted: false
  },
  {
    id: 'brand-supagas',
    name: 'Supagas (National Oil)',
    distributor: 'National Oil Corporation of Kenya (NOCK)',
    tagline: 'Government certified affordable and safe domestic LPG',
    badge: 'Govt Certified',
    color: '#16A34A',
    borderColor: 'border-green-600',
    bgLight: 'bg-green-50',
    valveType: 'Universal 20mm Compact',
    cylinderSizes: ['6 kg', '13 kg', '50 kg'],
    isAvailable: true,
    isDeleted: false
  },
  {
    id: 'brand-ola',
    name: 'Ola Energy (OiLGas)',
    distributor: 'Ola Energy Kenya Ltd',
    tagline: 'Ola premium domestic refill with calibrated net weight',
    badge: 'Certified Clean',
    color: '#2563EB',
    borderColor: 'border-blue-500',
    bgLight: 'bg-blue-50',
    valveType: 'Universal Compact',
    cylinderSizes: ['6 kg', '13 kg'],
    isAvailable: true,
    isDeleted: false
  },
  {
    id: 'brand-lake',
    name: 'Lake Gas',
    distributor: 'Lake Region Gas Ltd',
    tagline: 'Consistent burner pressure for home & restaurant',
    badge: 'Commercial Grade',
    color: '#4F46E5',
    borderColor: 'border-indigo-500',
    bgLight: 'bg-indigo-50',
    valveType: 'Standard Industrial Valve',
    cylinderSizes: ['6 kg', '13 kg', '50 kg'],
    isAvailable: true,
    isDeleted: false
  },
  {
    id: 'brand-hass',
    name: 'Hass Gas',
    distributor: 'Hass Petroleum Kenya',
    tagline: 'High grade clean energy burner with safety overfill shutoff',
    badge: 'High Heat',
    color: '#DC2626',
    borderColor: 'border-red-600',
    bgLight: 'bg-red-50',
    valveType: 'Universal Pin Valve',
    cylinderSizes: ['6 kg', '13 kg'],
    isAvailable: true,
    isDeleted: false
  },
  {
    id: 'brand-menengai',
    name: 'Menengai Gas',
    distributor: 'Menengai Oil Refineries LPG Div',
    tagline: 'Refined pure butane-propane mix with zero black smoke',
    badge: 'Clean Burn',
    color: '#9333EA',
    borderColor: 'border-purple-500',
    bgLight: 'bg-purple-50',
    valveType: 'Standard 20mm',
    cylinderSizes: ['6 kg', '13 kg'],
    isAvailable: true,
    isDeleted: false
  },
  {
    id: 'brand-safegas',
    name: 'Safe Gas',
    distributor: 'Safe Gas Kenya',
    tagline: 'Lightweight composite explosion-resistant domestic cylinders',
    badge: 'Composite Tech',
    color: '#0891B2',
    borderColor: 'border-cyan-600',
    bgLight: 'bg-cyan-50',
    valveType: 'Quick Snap-On Valve',
    cylinderSizes: ['6 kg', '13 kg'],
    isAvailable: true,
    isDeleted: false
  },
  {
    id: 'brand-jamvi',
    name: 'Jamvi Gas',
    distributor: 'Jamvi Energy Kenya',
    tagline: 'Everyday pocket-friendly cooking gas with strict weight testing',
    badge: 'Budget Friendly',
    color: '#D97706',
    borderColor: 'border-amber-600',
    bgLight: 'bg-amber-50',
    valveType: 'Standard Compact',
    cylinderSizes: ['6 kg', '13 kg'],
    isAvailable: true,
    isDeleted: false
  }
];
